// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYNKvTEzGDkQxWXRUbYYhWWFdtZW5z1uU',
    appId: '1:896347554502:web:ed2c869ca2fb34e33f8dc7',
    messagingSenderId: '896347554502',
    projectId: 'rubi-pasteleria-b397e',
    authDomain: 'rubi-pasteleria-b397e.firebaseapp.com',
    storageBucket: 'rubi-pasteleria-b397e.firebasestorage.app',
    measurementId: 'G-FDHJRXM4CF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdSvK2Pfe56S1ux-JJYgJ4zb28Yief88M',
    appId: '1:896347554502:android:a59baca7e9a14c4a3f8dc7',
    messagingSenderId: '896347554502',
    projectId: 'rubi-pasteleria-b397e',
    storageBucket: 'rubi-pasteleria-b397e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkglTD2EXUdofX33YOxjSfi7CRuwgbs98',
    appId: '1:896347554502:ios:6555157ce204c59f3f8dc7',
    messagingSenderId: '896347554502',
    projectId: 'rubi-pasteleria-b397e',
    storageBucket: 'rubi-pasteleria-b397e.firebasestorage.app',
    iosBundleId: 'com.example.rubiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkglTD2EXUdofX33YOxjSfi7CRuwgbs98',
    appId: '1:896347554502:ios:6555157ce204c59f3f8dc7',
    messagingSenderId: '896347554502',
    projectId: 'rubi-pasteleria-b397e',
    storageBucket: 'rubi-pasteleria-b397e.firebasestorage.app',
    iosBundleId: 'com.example.rubiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYNKvTEzGDkQxWXRUbYYhWWFdtZW5z1uU',
    appId: '1:896347554502:web:de10826f86ca79883f8dc7',
    messagingSenderId: '896347554502',
    projectId: 'rubi-pasteleria-b397e',
    authDomain: 'rubi-pasteleria-b397e.firebaseapp.com',
    storageBucket: 'rubi-pasteleria-b397e.firebasestorage.app',
    measurementId: 'G-Q8FZ8ZQHZ0',
  );

}